### ISSUE TITLE
Memory leak using query_method with large data sets

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/endpoints-proto-datastore#122]
This issue is regarding the query_method decorator and large data sets (> 1000 items).

We are experiencing high memory usage when performing queries on large data sets and limiting the results.  The memory seems to be allocated for the entire set, not just the results returned.  For example, a query for the first 100 entities from a dataset of 2000 will cause an extra 5 MB of RAM to be used on each request and this is never freed.  However, if the last 100 entities of the 2000 are requested, no additional memory is used.  If we set produce_cursors to False in the query options used in fetch_page, no nextPageToken is returned, and the behaviour is identical to requesting the last 100 entities (no additional memory used).  As a fix, we've added the following option to the query_method decorator in model.py (Nov 26, 2014, commit ed91623ae07b9ff2341d420e48ed940f40552828):

Line 1435:

```
def query_method(cls,
                 query_fields=(),
                 collection_fields=None,
                 limit_default=QUERY_LIMIT_DEFAULT,
                 limit_max=QUERY_LIMIT_MAX,
                 user_required=False,
                 use_projection=False,
                 produce_cursors=True,
                 **kwargs):
```

Line 1600:

```
query_options['produce_cursors'] = produce_cursors
items, next_cursor, more_results = query.fetch_page(
       request_limit, **query_options)
```

We then call the query_method with produce_cursors=False. Is there a better solution? Or could this fix be considered for implementation?

**Comment by dhermes** [comment]
@josemontesdeoca FYI

This is another report and gives some sample code for the memory leak in
https://code.google.com/p/googleappengine/issues/detail?id=9610

In particular, the peaks 185 MB / 199.8 MB of RAM stuck out in my memory after your comment about a peak of 300 MB.

**Comment by josemontesdeoca** [comment]
@dhermes Thanks for the notice! I'll definetly take a closer look
