### ISSUE TITLE
when entering field not from `choices` getting `503 Internal Server Error`

### ISSUE THREAD

**Issue by matantsu** [GoogleCloudPlatform/endpoints-proto-datastore#124]
implemented model as such:
```python
class MyModel(BaseModel):
    type = ndb.StringProperty(choices=['Plumber', 'Cleaner'])

...

    @MyModel.method(request_fields=('name' , 'type'),
                    path='professional',
                    name='professional.add')
    def addProfessional(self, pro):
        pro.put()
        return pro
```

when entering `type="myumyu"` getting:
```JSON
{
 "error": {
  "code": 503,
  "errors": [
   {
    "domain": "global",
    "message": "Internal Server Error",
    "reason": "backendError"
   }
  ],
  "message": "Internal Server Error"
 }
}
```

also in the API explorer i don't get a dropdown menu for selecting from the choices.
I also can't validate this myself because it crashes before it gets to my handler.

what would be ideal is for the api to say `type must be from ['Plumber', 'Cleaner']` or something like that.

**Comment by dhermes** [comment]
You should use a `protorpc` Enum via [`ndb.msgprop`][1].

```python
from protorpc import messages
from google.appengine.ext.ndb import msgprop

from endpoints_proto_datastore.ndb import EndpointsModel


class Type(messages.Enum):
  PLUMBER = 1
  CLEANER = 2

class MyModel(EndpointsModel):
  type = msgprop.EnumProperty(Type, required=True)

...
```

This produces the following schema in the discovery document:

```json
  "MyModelFoo": {
   "id": "MyModelFoo",
   "type": "object",
   "properties": {
    "id": {
     "type": "string",
     "format": "int64"
    },
    "type": {
     "type": "string",
     "enum": [
      "CLEANER",
      "PLUMBER"
     ],
     "enumDescriptions": [
      "",
      ""
     ]
    }
   }
  }
```

Though for some reason the APIs explorer doesn't give a dropdown.

[1]: https://cloud.google.com/appengine/docs/python/ndb/properties#msgprop

**Comment by dhermes** [comment]
@matantsu I'm closing this out because I think this answer accomplishes what you need.

Please re-open if you have remaining questions.

**Comment by matantsu** [comment]
thanks ! that works , although it misses the point of having the `choices` parameter...
why bother with it if it's not used ?

**Comment by dhermes** [comment]
Well it is used, both by the backend and by most clients. Just not by the
APIs explorer

Danny Hermes
