### ISSUE TITLE
Sending related entities with endpoint response.

### ISSUE THREAD

**Issue by aakashbapna** [GoogleCloudPlatform/endpoints-proto-datastore#128]
I wanted to send entities related to current entity in the response, so that the client doesn't have to do multiple round trips. Whats the best possible way to do this with endpoints-proto-datastore?

example-

```Python
class FeedItem(EndpointsModel):
    item_key = ndb.KeyProperty(kind="Item")
    feed_user_key = ndb.KeyProperty(kind="User")
```

In a response to a query for FeedItem, right now I am just sending keys in response. I wanted to send full Item and User objects to avoid roundtrips from client.

Solutions I tried-

1. Having entity as EndpointAliasProperty within Model-

```Python
    @EndpointsAliasProperty(property_type=Item.ProtoModel())
    def user_obj(self):
        return self.feed_user_key.get().ToMessage()
```

But, this is synchronous, would block when used in collection and would make duplicate calls when entities (like User) are repeated over.

 .2.  Using a custom message class-
```Python
class FeedResponseMessage(messages.Message):
    feed_items = messages.MessageField(FeedItem.ProtoCollection(), 1)
    related_users = messages.MessageField(User.ProtoCollection(), 2)
```
Here I can fetch the related entities the way I want (async, de-duped), but the entities in resulting response are in an array, client would have to loop through this to fetch the desired key. 
How can I create a map of ids <--> entities instead of array for a message field? 
```json
  { 
     "1234" : {
                    "name": "ABC"
                  },
     "4567" : {
                    "name": "BCD"
                   }
 }
```
This would make it easier to access on client.

**Comment by dhermes** [comment]
You can accomplish this with a `StructuredProperty`. Storing data you want via a `KeyProperty` is not the ["App Engine Way"][1]. Instead, it's typical to copy / denormalize data that you need loaded to make reads really fast.

Please re-open if this doesn't satisfy your needs.

[1]: http://bjk5.com/post/54202245691/the-app-engine-way
