### ISSUE TITLE
Endpoints isn't included in Managed VMs

### ISSUE THREAD

**Issue by Bekt** [GoogleCloudPlatform/endpoints-proto-datastore#131]
Endpoints is not included in the standard Python runtime. ([link](https://cloud.google.com/appengine/docs/managed-vms/#standard_runtimes))

Additionally, gcloud (needed for VM) ignores the `libraries` section in app.yaml. As a result, `endpoints` cannot be directly imported to the project. Thus, the project fails at runtime because of [line 15](https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/c4e0be48dea2b85e0c91c9f5c8bdcb44d2605e91/endpoints_proto_datastore/ndb/model.py#L15).

Two ways to fix:

1. (Preferred) Add endpoints to standard runtime in the Google-supplied Dockerfile.
2. Replace line 15 with: 
```py
try:
    import endpoints
except ImportError:
    from google.appengine.ext import endpoints
```

**Comment by dhermes** [comment]
@Bekt this library is an extension of `endpoints`, so the dockerfile stuff is outside of our scope.

Can you confirm that

```python
from google.appengine.ext import endpoints
```

works in managed VMs?

cc @kdeus

**Comment by Bekt** [comment]
@dhermes I agree about Dockerfile; I just mentioned about it here since I do not know where to file endpoints issues.

At least for now, `google.appengine.ext.endpoints` ([source](https://cloud.google.com/appengine/docs/python/endpoints/#endpoints_libraries_tools_and_samples)) seems to work.

Here's an example of an instance running on a VM: https://vm1-dot-kanat-dev.appspot.com/_ah/api/humanlink/v1/accounts/404

**Comment by kdeus** [comment]
Here is where Endpoints bugs are tracked:
https://code.google.com/p/googleappengine/issues/list?can=2&q=Component=Endpoints&sort=-id&colspec=ID%20Type%20Component%20Status%20Stars%20Summary%20Language%20Priority%20Owner%20Log

Thanks for the info on this one.  I've brought it to the team's attention.

**Comment by dhermes** [comment]
@kdeus Is there a new destination coming soon? (e.g. post code.google.com shutdown)

**Comment by kdeus** [comment]
And just to follow up, no word yet on a new destination for our public bug
tracker.

**Comment by dhermes** [comment]
Thanks. What are you waiting for? [March 12][1] was 84 days ago. Need help?

[1]: http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html

**Comment by kdeus** [comment]
That's part of the GAE team's public bug tracker, so our team is just
waiting for word from them if/where it'll be moving.  It's still functional
for the moment, and I haven't heard news of it moving elsewhere yet.

**Comment by dhermes** [comment]
Gotcher.
