### ISSUE TITLE
repeated StructuredProperty field is ignored in response when getting object

### ISSUE THREAD

**Issue by zdenulo** [GoogleCloudPlatform/endpoints-proto-datastore#134]
code example and detailed explanation is here https://github.com/zdenulo/epd-error-example

**Comment by dhermes** [comment]
Thanks for filing. I confirmed the issue and will hopefully have a fix today. Your fix may work fine, but it seems out of place since the `None` check comes right after `None` is used as a fall-back with `getattr`.

**Comment by dhermes** [comment]
FYI this fix is going in as #140. Thanks a lot! I'm closing since #138 also covers it.
