### ISSUE TITLE
Use @EndpointsAliasProperty just to fill request_fields but not to be put inside datastore

### ISSUE THREAD

**Issue by andiwinata** [GoogleCloudPlatform/endpoints-proto-datastore#141]
Hello,

I'm using endpoints-proto-datastore package to build the API. In my case, on the API Explorer, I want to have a field `auth-id` which just used for authentication.

so when I call `@MyClass.method` or `@MyClass.query` I can put `auth-id` field as the request field but when I call `model.put()` I don't want the `auth-id` to be stored into the datastore.

So I searched through the package and found the `@EndpointsAliasProperty` and its documentation is

> A custom property that also considers the type of the response.
> 
> Allows Python properties to be used in an EndpointsModel by also  
> specifying a property type. These properties can be derived from the
> rest   of the model and included in a ProtoRPC message definition, but
> will not need   to be persisted in the datastore.
> 
>   This class can be used directly to define properties or as a
> decorator.

This suits my need, but I don't know how to use it. When I see the example in http://endpoints-proto-datastore.appspot.com it does not really show what I want to do, can someone guide me how to use it?

Thanks

**Comment by dhermes** [comment]
Luckily for you, the express purpose of `@EndpointsAliasProperty` is to have fields which don't correspond to message fields.

To get the custom verification behavior, you'd want to pass a custom setter. From the [example][1]

> a setter which will be used by the helper property...The setter used for that helper...will be called when [the alias property] is set from a ProtoRPC... request.

[1]: https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/bf241d611d9aee4f0da6a6b39c31cdd9cbfad74c/examples/custom_alias_properties/main.py#L46-L49

**Comment by andiwinata** [comment]
Hey, thanks for the reply
I just got that working! 
and also one thing what does the `return` does in `@EndpointsAliasProperty`? right now I'm using it just to return random value since I just need the `setter`

**Comment by dhermes** [comment]
Are you familiar with a Python [`@property`][1]? That is essentially how `@EndpointsAliasProperty` works.

The setter is called when the API request is converted from a ProtoRPC object into your native `EndpointsModel` (subclass) object and the getter is used to convert values on your `EndpointsModel` object into whatever the property is supposed to be.

You may find that you just want to `raise NotImplementedError` if the getter is used.

[1]: https://docs.python.org/2/library/functions.html#property

**Comment by andiwinata** [comment]
Ah I see, so that's how it works, I'm fairly new to Python, just read about property. Thanks a lot for this library!

**Comment by dhermes** [comment]
Sure thing. Glad it helps!
