### ISSUE TITLE
path='model/{id}' does not show @EndpointsAliasProperty(required=True) in API Manager

### ISSUE THREAD

**Issue by andiwinata** [GoogleCloudPlatform/endpoints-proto-datastore#142]
Hello,

For example I have code like this
```
class SomeClass(EndpointsModel):

    def auth_id_set(self, value):
        ....
    
    @EndpointsAliasProperty(required=True, setter=auth_id_set)
    def auth_id(self):
         ....


@Mymodel.method(request_fields=('id', 'auth_id'), path='models/{id}')
def model_get_id(self, model):
    ...
```

So In API Manager, I could not see `auth_id` field and everytime I execute the request it will throw error because the `auth_id` field is required. Once I remove `{id}` from the `path`, it becomes how it is supposed to be.

Is this the intended behaviour?

Thanks

**Comment by dhermes** [comment]
The way you have it structured, `id` should go in the path and `auth_id` in the body. Are you referring to the API manager for a deployed app or with the dev appserver?

**Comment by andiwinata** [comment]
oh sorry i should have put `http_method='GET'`, that one was in dev app server, havent checked in the deployed app

**Comment by dhermes** [comment]
In a `GET` request your arguments can only come through the path. This is part of `endpoints` and isn't specific to this library.

I'd recommend going through
https://cloud.google.com/appengine/docs/python/endpoints/

Also, a question like this may be more appropriate for StackOverflow. Have you used that site?

**Comment by andiwinata** [comment]
Ah sorry, I'll do it in StackOverflow then

**Comment by dhermes** [comment]
No need to be sorry, I'm happy to help.
