### ISSUE TITLE
Resource IDs and Field Lists

### ISSUE THREAD

**Issue by pdugas** [GoogleCloudPlatform/endpoints-proto-datastore#145]
This is more of a request for guidance, and a suggestion that I may not be alone in not understanding something, more than a real issue...

It seems that by default, the `id` field is not included in the response fields when GET'ing an individual resource or a list of them.  This seems odd to me.  The apps I build typically start with a "login" AJAX call that returns and Account entity.  From there, I usually load lists of secondary resources the user has access to. Later, I may want to update those secondary resources or load tertiary resources and so on.  My models currently use KeyProperty fields for the references. By default, I don't have any of the `id` values I need to load the secondary and tertiary resources.  

I end up having to manually specify the list of properties by setting `_message_fields_schema` in my Account model class.  

First question - Is there a way to add "id" to the message fields without having to replace the logic that automatically figures out the fields by default?

Second question - Is there a way to adjust the default logic to have KeyProperty fields appear "on the wire" as just their `id` values instead of the key hash that we get now? 

Apologies in advance if this is off base.  Kids just got out of school and working from home just got weird.  I'm not yet focusing well but I'm really looking to figure out the "right" way to make this work.  I really like the concept of this project.  Great stuff.

**Comment by dhermes** [comment]
The easiest hack to get this working (for now) would be to modify `_message_fields_schema` after class creation.

```python
class Account(EndpointsModel):
    ...

Account._message_fields_schema._data += ('id,')
```

I've toyed with your suggestion but haven't ever found a great way to specify the "extra" fields (there might be an old issue with a discussion even).

**Comment by pdugas** [comment]
Ah, a nifty hack.  I didn't think about doing it outside the class definition.  Will try that today.

How about the second par?  Say my Account model has a property like so, `groups=KeyProperty(Group, repeated=True)`.  Any ideas how to have this appear as `group_ids: [123, 234, 345]` on the wire?

**Comment by pdugas** [comment]
That `Account._message_fields_schema._data += ('id',)` hack works.  Thanks.

**Comment by pdugas** [comment]
Instead of changing the logic to emit `key.id()` for KeyProperty fields, how hard would it be to have the stock API accept `key` as a query field instead of (or in addition to) `id`.

**Comment by dhermes** [comment]
Converting a list of `Key` entities to integers, you'd want an alias property. I'd recommend http://endpoints-proto-datastore.appspot.com/examples/custom_alias_properties.html or http://endpoints-proto-datastore.appspot.com/examples/matching_queries_to_indexes.html or http://endpoints-proto-datastore.appspot.com/examples/keys_with_ancestors.html for examples using an alias property.

I recommend reading every example on http://endpoints-proto-datastore.appspot.com/

At this point, I'm going to close this issue out. If you have more "how can I" questions, please ask on StackOverflow and I'm happy to answer there.
