### ISSUE TITLE
Required = True forced on query_method

### ISSUE THREAD

**Issue by zrothberg** [GoogleCloudPlatform/endpoints-proto-datastore#149]
```python
class Task(EndpointsModel):
    name = ndb.StringProperty(required=True)
    stress_level = ndb.IntegerProperty(required=True)
    difficulty = ndb.IntegerProperty(choices=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    time = ndb.DateTimeProperty(auto_now_add=True)
    description = ndb.TextProperty()
    owner = ndb.UserProperty(required=True)


    @Task.query_method(user_required=True,
                       name = 'task.list',
                       path = 'task',
                       query_fields=('stress_level', 'difficulty', 'name'),
                       http_method = 'GET')#this part is not needed as GET is default
    def list_tasks(self, query):
        return query
```

With the above classes running a query without the fields throws the following error (`400 Bad Request`):

```json
{
 "error": {
  "code": 400,
  "errors": [
   {
    "domain": "global",
    "message": "Error parsing ProtoRPC request (Unable to parse request content: Message CombinedContainer is missing required field stress_level)",
    "reason": "badRequest"
   }
  ],
  "message": "Error parsing ProtoRPC request (Unable to parse request content: Message CombinedContainer is missing required field stress_level)"
 }
}
```

There was a stackoverflow [question][1] about this also. I am unsure if this is a bug or just me and another person miss understanding behavior. 

[1]: http://stackoverflow.com/questions/40120820/endpoints-proto-datastore-field-should-be-required-on-post-but-not-get

**Comment by dhermes** [comment]
It seems like the request didn't sent a required field (`stress_level`). By default, the fields in a protobuf message class are [created][1] directly from your specification.

If you want the field to be optional, the easiest way is to just create your own custom proto class. However, custom request classes can only be used with `method`:

```python
@Foo.method(request_message=MyProtoClass, ...)
```

[1]: https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/99bed0b39762a86606dd22de57b5eaf1cfa8f40f/endpoints_proto_datastore/ndb/model.py#L954-L956

**Comment by zrothberg** [comment]
Sorry for the late reply. Thank you, cleared up the issue for me. Do you mind if I cite this on the stackoverflow question in case anyone reads it looking for the same issue?

**Comment by dhermes** [comment]
Not at all.

**Comment by tmst** [comment]
I don't completely follow the logic for closing this. The issue seems to be that because a field is specified as required in the model, a query not containing the field as a parameter will fail. So every possible query must filter on a value of this field? This seems like a bug, as a query should execute given any subset of the fields of the model. The obvious result seems to be that no fields may be designated required.

BTW, I'm having tremendous success using this library (Thank you, Dan). When I observed this behavior I immediately assumed it to be a bug.

**Comment by dhermes** [comment]
@tmst Sorry I missed this comment. I assume this is what led to the discussion in #151?

**Comment by tmst** [comment]
No problem. In way, yes. But I believe they are separate, if closely-related, issues.
