### ISSUE TITLE
Required = True forced on query_method

### ISSUE THREAD

**Issue by tmst** [GoogleCloudPlatform/endpoints-proto-datastore#151]
This seems like an unresolved bug to me, so I'm adding it again. It shouldn't be necessary to define a ProtoBuf class as a workaround to get the expected behavior from `query_method` in which a query is executed without filtering on any and all fields designated as required in the model.

**Comment by dhermes** [comment]
@tmst IIRC `required=True` is only forced if the field itself has `required=True`, i.e.

```python
import endpoints
from google.appengine.ext import ndb

from endpoints_proto_datastore.ndb import EndpointsModel


class MyModel(EndpointsModel):

  attr = ndb.StringProperty(required=True)
```

Is this what you mean?

**Comment by tmst** [comment]
I think not exactly. It's simply that no simple query without filters will succeed if *any* field of the model is designated required.

**Comment by dhermes** [comment]
Oh really? Can you provide a simple example that indicates such a failed query?

**Comment by tmst** [comment]
In your example above, the following returns an error about missing 'attr':

    class MyModelService(remote.Service):
        @MyModel.query_method(query_fields = ('attr', ))
        def list(query):
            query.filter()

**Comment by dhermes** [comment]
Got it, we were on the same page but I didn't realize it.

I'm not sure I agree that it is broken. The model for the query says the field is required. If we didn't support that, people would come on the other side and say "you let bad queries through, my model said that property is required".

**Comment by tmst** [comment]
But we're just *listing* entities! Why should all required properties be filtered on?

**Comment by dhermes** [comment]
@tmst I understand the argument against, I just don't think it's possible to please all users here.

A "fix" would be to subclass `ndb.StringProperty` (and all the other properties) and provide extra property arguments like `model_required=True, query_required=False`.

I'd be happy to review a PR if you were interested in trying your hand at such a feature.

**Comment by tmst** [comment]
OK. This is weird. I can't believe we're talking about the same thing. If this were a relational db, should it not be possible to say, "Select * from MyModel", with no "where" clause?

**Comment by dhermes** [comment]
It's definitely possible to do, it's just about ambiguous interpretation of the `required=True` field. You can still do it, just not with the default query schema that comes with the model.

FWIW I think the current implementation is far from perfect, I just don't want to pull the rug out from people who have been using this "feature" (more like "accidental behavior").

**Comment by tmst** [comment]
I understand, and may try the workaround you suggest. Thanks for your patience.

**Comment by dhermes** [comment]
Sure thing. I appreciate that you came by to discuss and am happy this library has been useful to you.

**Comment by theacodes** [comment]
@dhermes and I actually did a silly thing were we both implemented the same utility with vastly different approaches, so if you're running into intractable issues with this library you might consider giving [protopigeon](https://github.com/jonparrott/Protopigeon) a look, if it still works. :P

**Comment by tmst** [comment]
Hi, Jon! Yeah, I've been toying with idea of going back to try out Ferris3 again now that I have a better grasp of the concepts involved.

**Comment by theacodes** [comment]
Disclaimer: I don't maintain it anymore. But a lot of that code is straightforward. Protopigeon are ferris3 are ripe for code raiding.

**Comment by tmst** [comment]
There's also the new? Google Endpoints. Might some of this find its way into that?

**Comment by theacodes** [comment]
Endpoints v2 does away with the protobuf requirement. Endpoints Frameworks for App Engine standard has the same interface as the old endpoints libraries. So, nothing really changes for standard users.

**Comment by tmst** [comment]
Does that mean that custom message classes no longer need be defined?

**Comment by theacodes** [comment]
For standard, nothing changes at the application level. It's all just infrastructure changes.

**Comment by tmst** [comment]
Thanks. Apparently I need to clarify to myself how all these relate to one another: "standard", "old endpoints libraries" and "v2".

**Comment by tmst** [comment]
Just a note: Another side effect of this implementation is that a query incorrectly raises a 404 unless there are entities having having the specified value for the required property, whereas an empty list should instead be returned.

**Comment by tmst** [comment]
It just occurred to me that one good thing about the current implementation is that it probably prevents some new users from inadvertently downloading large data sets. :-)
