### ISSUE TITLE
Partial fields mask in API Explorer not supported

### ISSUE THREAD

**Issue by tmst** [GoogleCloudPlatform/endpoints-proto-datastore#155]
In API Explorer, when executing any operation (GET, UPDATE, etc), selecting the fields to be returned in a partial response using the partial fields mask in the fields editor has no effect.

TTBOMK, any of the EPD examples can be used to demonstrate this issue. Also, the problem probably also extends to requests with curl or various client libraries, but I haven't verified this.

I believe any server settings, such as the `response_fields` parameter to the `EndpointsModel.method` decorator, should be overridden by the request's `fields` parameter to further restrict the response.

**Comment by dhermes** [comment]
I'm fairly certain this is a bug in the API explorer. If not, it's a bug (or feature?) in the core endpoints code, not this library.

Either way, it can't be fixed here.

Mind if we close this issue? I can try to help you redirect to the App Engine bug tracker if you're not sure how (I'm not sure either, but I can ask some Googlers).

**Comment by tmst** [comment]
Sure. Makes sense that it's further up the stack. I'll submit it on the App Engine tracker.
