### ISSUE TITLE
Support db in the same fashion the ndb is supported

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/endpoints-proto-datastore#18]
Support `db` in the same fashion the `ndb` is supported.

This would be in the package

```
endpoints_proto_datastore.db
```

and would force an update to [`_GetEndpointsMethodDecorator`][1].

[1]: https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/blob/5ccd11bbeb78b05cb093986d3977834f6630b41e/endpoints_proto_datastore/utils.py#L361

<sub>**NOTE:** THIS POST WAS EDITED AFTER BEING MIGRATED.</sub>

---
---

<sub>**Code Hosting Comment Metadata:**</sub>
<sub>author.htmlLink=https://code.google.com/u/dhermes@google.com/</sub>
<sub>author.name=dhermes@google.com</sub>
<sub>id=0</sub>
<sub>published=2013-02-03T00:15:47.000Z</sub>

<sub>**Code Hosting Issue Metadata:**</sub>
<sub>published=2013-02-03T00:15:47.000Z</sub>
<sub>stars=1</sub>
<sub>updated=2013-02-03T00:16:31.000Z</sub>
<sub>originalIssue=https://code.google.com/p/endpoints-proto-datastore/issues/detail?id=42</sub>
<sub>author=@dhermes</sub>

**Comment by dawhum** [comment]
Are there still plans to develop a db package?

**Comment by dhermes** [comment]
@dawhum Is there a reason you don't use `ndb`?

**Comment by dawhum** [comment]
@dhermes The application was created before ndb was introduced. Given ndb's backwards incompatibility with db, we don't have budget for, and it's difficult to justify, major refactoring of the application.

**Comment by dhermes** [comment]
You can talk to the same data with both `db` and `ndb`, so you won't need to rewrite your other code to be able to use this library.

If you want to create `EndpointsModel` classes for interacting with your data it's virtually the same, the only real difference being that `ndb` caches both in memory and in `memcache`. You can turn both of these off on the class by simple saying:

```python
from google.appengine.ext import ndb
from endpoints_proto_datastore.ndb import EndpointsModel

class MyModel(EndpointsModel):
    _use_cache = False
    _use_memcache = False
    my_prop = ndb.StringProperty(required=True)
```

**Comment by dawhum** [comment]
@dhermes Thank you. It makes sense. However, we have a number of extensive models, so all in all, it'd still take a substantial rewrite (or maintaining complex duplicate models).

**Comment by dhermes** [comment]
Yes it seems difficult, unfortunately, this library won't be supporting `db`.

I'm happy to continue the conversation to help you figure out how it can work for you in its current state.

**Comment by dawhum** [comment]
Thank you, @dhermes. I'll think about it and let you know. In the meantime, do you think it would make sense to remove the accepted tag from this given it's no longer expected to be implemented?

**Comment by dhermes** [comment]
For sure! Thanks for pointing that out.
