### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/endpoints-proto-datastore#90]
Any reason we shouldn't push `endpoints-proto-datastore` to [pypi](pypi.python.org)?

**Comment by btelles** [comment]
@proppy , @webmaven and @dhermes , looks like the currently published pip version points to a non-existent readme. It points to "README.md" but the file doesn't exist in the package. I see that it exists in the repo though. Any chance one of you could bump the version and push it with the right paths?

**Comment by webmaven** [comment]
@btelles, I don't have commit permissions on this repo. @proppy and @dhermes, do you need a PR?

**Comment by dhermes** [comment]
Sorry for slow response. Yes, please send a PR and I'm happy to accept.

**Comment by fisherds** [comment]
My two cents:
Moving to pypi so developers can use the `-t lib` pip install approach is now necessary to feel like a modern App Engine tool.

Rational:
Given that the Endpoints 2.0 library also uses the `-t lib` approach for library installations.  

[https://cloud.google.com/appengine/docs/python/endpoints/migrating](https://cloud.google.com/appengine/docs/python/endpoints/migrating)

it seems like the momentum to use that approach is now VERY clear.  Most other 3rd party libraries have made that move long ago too.  It is now really awkward that endpoints-proto-datastore isn't using the `-t lib` installation approach.  To feel like a modern tool this library needs to join pypi to join the standard way to do installations.  Obviously my motivation is more for the sake of perception than functionality.  That said perception is important too. :)

**Comment by dhermes** [comment]
@fisherds this library is already on PyPI so feel free to install into lib as is typical

**Comment by webmaven** [comment]
@dhermes, then is there any reason not to close this issue?

**Comment by dhermes** [comment]
https://pypi.python.org/pypi/endpoints-proto-datastore

**Comment by fisherds** [comment]
Didn't actually work for me when I tried to run `pip install -t lib endpoints-proto-datastore`.  Thoughts?  Here is the error message that I got:

```
davids-mbp-2:gae-project fisherds$ pip install -t lib endpoints-proto-datastore
Collecting endpoints-proto-datastore
  Downloading endpoints-proto-datastore-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nx/khq618616mg1nmqhy70spkx00000gn/T/pip-build-CIovkJ/endpoints-proto-datastore/setup.py", line 6, in <module>
        LONG_DESCRIPTION = open(README_FILENAME).read()
    IOError: [Errno 2] No such file or directory: '/private/var/folders/nx/khq618616mg1nmqhy70spkx00000gn/T/pip-build-CIovkJ/endpoints-proto-datastore/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nx/khq618616mg1nmqhy70spkx00000gn/T/pip-build-CIovkJ/endpoints-proto-datastore/
davids-mbp-2:gae-project fisherds$ 

```

**Comment by dhermes** [comment]
Looks like no one has ever installed the package, d'oh! Missing a `MANIFEST.in` did us in.

Just uploaded a new version:
https://pypi.python.org/pypi/endpoints-proto-datastore/0.10.0
